// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShopAAA.DataDB;

#nullable disable

namespace WebShopAAA.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230130134211_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "21bec614-e9b0-40c3-83d6-641ec69cadaf",
                            ConcurrencyStamp = "9227c71f-b196-469c-8cea-a9c86baa84b0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "ba8e4f63-29d4-4b45-a571-b5c707c07542",
                            ConcurrencyStamp = "af0e4cd7-a123-4ba8-9744-1280f801cf00",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4c6f6966-7ef5-4a30-80f0-5977fdb62099",
                            RoleId = "21bec614-e9b0-40c3-83d6-641ec69cadaf"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.Property<int>("CategorysId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategorysId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("ProductProductCategory");

                    b.HasData(
                        new
                        {
                            CategorysId = 1,
                            ProductsId = 1
                        },
                        new
                        {
                            CategorysId = 2,
                            ProductsId = 2
                        },
                        new
                        {
                            CategorysId = 3,
                            ProductsId = 3
                        },
                        new
                        {
                            CategorysId = 4,
                            ProductsId = 4
                        },
                        new
                        {
                            CategorysId = 5,
                            ProductsId = 5
                        },
                        new
                        {
                            CategorysId = 5,
                            ProductsId = 6
                        },
                        new
                        {
                            CategorysId = 4,
                            ProductsId = 7
                        },
                        new
                        {
                            CategorysId = 2,
                            ProductsId = 8
                        },
                        new
                        {
                            CategorysId = 1,
                            ProductsId = 9
                        },
                        new
                        {
                            CategorysId = 4,
                            ProductsId = 10
                        },
                        new
                        {
                            CategorysId = 1,
                            ProductsId = 11
                        },
                        new
                        {
                            CategorysId = 6,
                            ProductsId = 12
                        },
                        new
                        {
                            CategorysId = 2,
                            ProductsId = 13
                        },
                        new
                        {
                            CategorysId = 2,
                            ProductsId = 14
                        },
                        new
                        {
                            CategorysId = 2,
                            ProductsId = 15
                        },
                        new
                        {
                            CategorysId = 2,
                            ProductsId = 16
                        },
                        new
                        {
                            CategorysId = 1,
                            ProductsId = 17
                        },
                        new
                        {
                            CategorysId = 2,
                            ProductsId = 18
                        },
                        new
                        {
                            CategorysId = 1,
                            ProductsId = 19
                        },
                        new
                        {
                            CategorysId = 4,
                            ProductsId = 20
                        },
                        new
                        {
                            CategorysId = 1,
                            ProductsId = 21
                        },
                        new
                        {
                            CategorysId = 1,
                            ProductsId = 22
                        },
                        new
                        {
                            CategorysId = 3,
                            ProductsId = 23
                        });
                });

            modelBuilder.Entity("WebShopAAA.Models.ApplicationUserModel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modilephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Phonenummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4c6f6966-7ef5-4a30-80f0-5977fdb62099",
                            AccessFailedCount = 0,
                            Address = "adminsgatan",
                            City = "GBG",
                            ConcurrencyStamp = "bdd9277d-be21-4403-8955-ca83eb4d2dc4",
                            Country = "Swedan",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 729, DateTimeKind.Local).AddTicks(3264),
                            Email = "Admin1@admin.com",
                            EmailConfirmed = false,
                            FirstName = "admin",
                            LastName = "admin",
                            LockoutEnabled = false,
                            Modilephone = "987654321",
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEB22Bw4ZYGKoWuGNb2byLxfXkomVfPyes+PXNM0UNO9i7WE3qcAJvFrgPNGV+xtBCg==",
                            PhoneNumberConfirmed = false,
                            Phonenummer = "0123456",
                            PostCode = "444 44",
                            SecurityStamp = "a165344b-3936-4480-81c8-283ed9022d8f",
                            TwoFactorEnabled = false,
                            UserName = "Admin@admin.com"
                        });
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPicked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderItems")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PaymentDetails")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderItems");

                    b.HasIndex("PaymentDetails");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderDetailsId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailsId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.PaymentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderDetails")
                        .HasColumnType("int");

                    b.Property<bool>("Satus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetails");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArtNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderItems")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItems");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtNumber = "1212",
                            Color = "#00ff00",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5019),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "001.jpg",
                            ModelName = "marcos",
                            Name = "accent chair",
                            Price = 25999,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 2,
                            ArtNumber = "1212",
                            Color = "#ffb900",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5037),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "002.jpg",
                            ModelName = "liddy",
                            Name = "albany sectional",
                            Price = 1099,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 3,
                            ArtNumber = "1212",
                            Color = "#ffb900",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5047),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "003.jpg",
                            ModelName = "liddy",
                            Name = "albany table",
                            Price = 10555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 4,
                            ArtNumber = "1212",
                            Color = "#0000ff",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5056),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "004.jpg",
                            ModelName = "marcos",
                            Name = "armchair",
                            Price = 15555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 5,
                            ArtNumber = "1212",
                            Color = "#000",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5108),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "005.jpg",
                            ModelName = "liddy",
                            Name = "bar stool",
                            Price = 155,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 6,
                            ArtNumber = "1212",
                            Color = "#ffb900",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5122),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "006.jpg",
                            ModelName = "ikea",
                            Name = "dining table",
                            Price = 10885,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 7,
                            ArtNumber = "1212",
                            Color = "#0000ff",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5131),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "007.jpg",
                            ModelName = "ikea",
                            Name = "emperor bed",
                            Price = 1775,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 8,
                            ArtNumber = "1212",
                            Color = "#ff0000",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5140),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "008.jpg",
                            ModelName = "caressa",
                            Name = "entertainment center",
                            Price = 1995,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 9,
                            ArtNumber = "1212",
                            Color = "#00ff00",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5149),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "009.jpg",
                            ModelName = "ikea",
                            Name = "high-back bench",
                            Price = 1555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 10,
                            ArtNumber = "1212",
                            Color = "#ffb900",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5160),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "010.jpg",
                            ModelName = "caressa",
                            Name = "leather chair",
                            Price = 555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 11,
                            ArtNumber = "1212",
                            Color = "#0000ff",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5168),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "011.jpg",
                            ModelName = "caressa",
                            Name = "leather sofa",
                            Price = 33555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 12,
                            ArtNumber = "1212",
                            Color = "#ff0000",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5177),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "012.jpg",
                            ModelName = "caressa",
                            Name = "modern bookshelf",
                            Price = 1255,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 13,
                            ArtNumber = "1212",
                            Color = "#000",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5186),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "013.jpg",
                            ModelName = "liddy",
                            Name = "modern poster",
                            Price = 10555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 14,
                            ArtNumber = "1212",
                            Color = "#00ff00",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5194),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "014.jpg",
                            ModelName = "ikea",
                            Name = "shelf",
                            Price = 555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 15,
                            ArtNumber = "1212",
                            Color = "#0000ff",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5203),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "015.jpg",
                            ModelName = "liddy",
                            Name = "simple chair",
                            Price = 155,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 16,
                            ArtNumber = "1212",
                            Color = "#ffb900",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5212),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "016.jpg",
                            ModelName = "marcos",
                            Name = "sofa set",
                            Price = 555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 17,
                            ArtNumber = "1212",
                            Color = "#00ff00",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5221),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "017.jpg",
                            ModelName = "caressa",
                            Name = "suede armchair",
                            Price = 1555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 18,
                            ArtNumber = "1212",
                            Color = "#00ff00",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5232),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "018.jpg",
                            ModelName = "liddy",
                            Name = "utopia sofa",
                            Price = 22555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 19,
                            ArtNumber = "1212",
                            Color = "#ff0000",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5241),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "019.jpg",
                            ModelName = "marcos",
                            Name = "vase table",
                            Price = 555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 20,
                            ArtNumber = "1212",
                            Color = "#ffb900",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5250),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "020.jpg",
                            ModelName = "ikea",
                            Name = "wooden bed",
                            Price = 1555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 21,
                            ArtNumber = "1212",
                            Color = "#000",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5259),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "021.jpg",
                            ModelName = "ikea",
                            Name = "wooden desk",
                            Price = 555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 22,
                            ArtNumber = "1212",
                            Color = "#0000ff",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5268),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "022.jpg",
                            ModelName = "ikea",
                            Name = "wooden desk",
                            Price = 8555,
                            Quantity = 3,
                            Size = "medium"
                        },
                        new
                        {
                            Id = 23,
                            ArtNumber = "1212",
                            Color = "#ffb900",
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5279),
                            Desc = "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
                            ImagePath = "023.jpg",
                            ModelName = "caressa",
                            Name = "wooden table",
                            Price = 10555,
                            Quantity = 3,
                            Size = "medium"
                        });
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(4900),
                            Desc = "office",
                            Name = "office"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(4959),
                            Desc = "living room",
                            Name = "living room"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(4971),
                            Desc = "kitchen",
                            Name = "kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(4981),
                            Desc = "bedroom",
                            Name = "bedroom"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(4990),
                            Desc = "dining",
                            Name = "dining"
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2023, 1, 30, 14, 42, 10, 716, DateTimeKind.Local).AddTicks(5003),
                            Desc = "kids",
                            Name = "kids"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebShopAAA.Models.ApplicationUserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebShopAAA.Models.ApplicationUserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShopAAA.Models.ApplicationUserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebShopAAA.Models.ApplicationUserModel.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductProductCategory", b =>
                {
                    b.HasOne("WebShopAAA.Models.Tables.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategorysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShopAAA.Models.Tables.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.OrderDetails", b =>
                {
                    b.HasOne("WebShopAAA.Models.ApplicationUserModel.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("OrderItems");

                    b.HasOne("WebShopAAA.Models.Tables.PaymentDetails", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentDetails");

                    b.Navigation("Payment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.OrderItems", b =>
                {
                    b.HasOne("WebShopAAA.Models.Tables.OrderDetails", null)
                        .WithMany("OrderItemId")
                        .HasForeignKey("OrderDetailsId");
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.PaymentDetails", b =>
                {
                    b.HasOne("WebShopAAA.Models.Tables.OrderDetails", "OrderId")
                        .WithMany()
                        .HasForeignKey("OrderDetails");

                    b.Navigation("OrderId");
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.Product", b =>
                {
                    b.HasOne("WebShopAAA.Models.Tables.OrderItems", "OrderId")
                        .WithMany()
                        .HasForeignKey("OrderItems");

                    b.Navigation("OrderId");
                });

            modelBuilder.Entity("WebShopAAA.Models.Tables.OrderDetails", b =>
                {
                    b.Navigation("OrderItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
